# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WangZhiLue
email: lue007@qq.com
description: WangZhiLue's Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hahahh0.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  hahahh0
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown

gitment:
  enable: true
  mint: true # RECOMMEND, A mint on Gitment, to support count, language and proxy_gateway
  count: true # Show comments count in post meta area
  lazy: false # Comments lazy loading with a button
  cleanly: false # Hide 'Powered by ...' on footer, and more
  language: # Force language, or auto switch by theme
  github_user: {hahahh0}
  github_repo: hahahh0.github.io
  client_id: {47cc9cf1be766d07a603}
  client_secret: {f8fa705220d18e094fdf92b4e16ce43042d7bf7c}
  proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
  redirect_protocol: # Protocol of redirect_uri with force_redirect_protocol when mint enabled
